replicaCount: 1

environment: dev
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: simple-web-dev.local
      paths:
        - path: /
          pathType: Prefix

  tls: []

html:
  indexHtml: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Simple Web App Dev</title>
    </head>
    <body>
      <h1>Hello from Helm! This is the Dev Environment</h1>
    </body>
    </html>

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
