replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: simple-web.local
      paths:
        - path: /
          pathType: Prefix

  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
